### ISSUE TITLE
请问最新升级这个EFI能支持Snoma14的WIFI吗?

### ISSUE THREAD

**Issue by derek926** [hackintosh-club/MAG-B460M-MORTAR-OpenCore#1]
配置与你相近，前几天升级过Sonoma，没有wifi功能，又退回来了😅

**Comment by WuLongMiTaoLaiYiDa** [comment]
> 配置与你相近，前几天升级过Sonoma，没有wifi功能，又退回来了😅

14 系统后的博通都需要OCLP补丁才能正常使用

**Comment by derek926** [comment]
好的，谢谢您！发自我的 iPhone在 2024年10月15日，09:34，summer ***@***.***> 写道：﻿

配置与你相近，前几天升级过Sonoma，没有wifi功能，又退回来了😅

14 系统后的博通都需要OCLP补丁才能正常使用
